digital_store/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/', views.add_to_cart,
         name='add_to_cart'),
    path('del_from_cart/', views.del_from_cart,
         name='del_from_cart'),
    path('make_order/', views.make_order, name='make_order'),
    path('add_count_items/', views.add_count_items,
         name='add_count_items'),
    path('remove_count_items/', views.remove_count_items,
         name='remove_count_items'),
    path('', views.cart, name='cart'),
]

digital_store/digital_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('moderation/', include('moderation.urls')),
    path('review/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]


handler404 = 'core.views.page_not_found'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

digital_store/moderation/urls.py
from django.urls import path

from . import views

app_name = 'moderation'

urlpatterns = [
     path('shops/', views.moderation_shop, name='moderation_shop'),
     path('accept_shop/<int:shop_id>/', views.accept_shop, name='accept_shop'),
     path('reject_shop/<int:shop_id>/', views.reject_shop, name='reject_shop'),
     path('products/', views.moderation_product, name='moderation_product'),
     path('accept_product/<int:product_id>/', views.accept_product,
          name='accept_product'),
     path('reject_product/<int:product_id>/', views.reject_product,
          name='reject_product'),
     path('moderation_history/', views.moderation_history,
          name='moderation_history'),
     path('change_moderator_status/', views.change_moderator_status,
          name='change_moderator_status'),
]

digital_store/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/<int:shop_id>/', views.shop, name='shop'),
    path('product/<int:product_id>/', views.product, name='product'),
    path('create_shop/', views.create_shop, name='create_shop'),
    path('edit_shop/<int:shop_id>/', views.edit_shop, name='edit_shop'),
    path('delete_shop/<int:shop_id>/', views.delete_shop, name='delete_shop'),
    path('shop/<int:shop_id>/create_product/', views.create_product,
         name='create_product'),
    path('shop/<int:shop_id>/edit_product/<int:product_id>/',
         views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product,
         name='delete_product'),
    path('product/<int:product_id>/create_item/', views.create_item,
         name='create_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('shops/', views.shop_list, name='shop_list'),
    path('products/', views.product_list, name='product_list'),
    path('search/', views.search, name='search'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('', views.index, name='index'),
]

digital_store/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('favorites/', views.get_favorite_list, name='favorites'),
    path('change_favorite/', views.change_favorite, name='change_favorite'),
    path('profile/<slug:username>/', views.user_profile, name='user_profile'),
    path('orders/', views.order_list, name='orders'),
    path('shops/<slug:username>/', views.get_user_shop_list, name='shops'),
    path('products/<slug:username>', views.get_user_product_list,
         name='products'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

digital_store/shop/models.py
from django.db import models

from cart.models import Cart
from users.models import Favorite, User

PRODUCT_AND_SHOP_STATUS = (
        ('Accept', 'Одобрено'),
        ('Reject', 'Отклонено'),
        ('In_Consideration', 'В рассмотрении'),
    )

DEFAULT_STATUS = PRODUCT_AND_SHOP_STATUS[-1][0]

ITEM_STATUS = (
    ('in_cart', 'В корзине'),
    ('sold', 'Продан'),
    ('sale', 'Продается')
)


class Shop(models.Model):
    """
    Модель магазина
    """

    name = models.CharField(
        max_length=128,
        unique=True,
        verbose_name='Название',
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Владелец',
        related_name='owner',
    )
    image = models.ImageField(
        default=None,
        upload_to='shop',
        verbose_name='Изображение',
        blank=True,
    )
    description = models.CharField(
        max_length=1028,
        verbose_name='Описание',
    )
    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
    )
    status = models.CharField(
        max_length=32,
        choices=PRODUCT_AND_SHOP_STATUS,
        default=DEFAULT_STATUS,
    )

    def __str__(self):
        return self.name

    def save(self, delete=False, *args, **kwargs):
        if delete:
            Cart.objects.filter(product__shop=self).delete()
            Favorite.objects.filter(product__shop=self).delete()
        super(Shop, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Магазин'
        verbose_name_plural = 'Магазины'


class Category(models.Model):
    """
    Модель категорий товаров
    """

    name = models.CharField(
        max_length=128,
        verbose_name='Название',
    )

    slug = models.SlugField(
        unique=True,
        max_length=20,
        verbose_name='Уникальный адрес категории',
    )

    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    """
    Модель продукта
    """

    name = models.CharField(
        max_length=128,
        verbose_name='Название',
    )
    shop = models.ForeignKey(
        Shop,
        on_delete=models.CASCADE,
        related_name='products',
        verbose_name='Магазин',
    )
    price = models.PositiveIntegerField(
        verbose_name='Цена',
    )
    category = models.ManyToManyField(
        Category,
        blank=True,
        related_name='category',
        verbose_name='Категория',
    )
    image = models.ImageField(
        default=None,
        upload_to='shop/product/',
        verbose_name='Изображение',
        blank=True,
    )
    description = models.CharField(
        max_length=1024,
        verbose_name='Описание',
    )
    count = models.PositiveIntegerField(
        default=0,
        verbose_name='Количество товара'
    )
    visibile = models.BooleanField(
        default=True,
        verbose_name='Видимость продукта',
    )
    status = models.CharField(
        max_length=32,
        choices=PRODUCT_AND_SHOP_STATUS,
        default=DEFAULT_STATUS,
    )
    is_available = models.BooleanField(
        default=False,
        verbose_name='В наличии'
    )
    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
    )

    def save(self, delete=False, *args, **kwargs):
        if self.count > 0:
            self.is_available = True
        else:
            self.is_available = False
        if delete:
            Cart.objects.filter(product=self).delete()
            Favorite.objects.filter(product=self).delete()
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Item(models.Model):
    """
    Модель отдельного товара в продукте
    """

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='item',
        verbose_name='Продукт',
    )
    item = models.CharField(
        max_length=1024,
        verbose_name='Товар',
    )
    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    status = models.CharField(
        default='sale',
        max_length=32,
        choices=ITEM_STATUS,
        verbose_name='Статус товара',
    )

    def __str__(self):
        return self.item

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

digital_store/templates/includes/card.html
{% load thumbnail %}
{% load static %}
{% comment %} <div class="product-link"> {% endcomment %}
{% if product.is_available is False and request.resolver_match.view_name != 'moderation:moderation_product'%}
  <div class="is_unavailable">
{% else %}
    <div>
{% endif %}
      <div class="col">
        <div class="box-with-shadow">
          <div class="card shadow-sm">
            <!--Изображение товара-->
              {% if product.image %}
                {% thumbnail product.image "410x320" crop="center" as im %}
                  <img class="card-img top" src="{{ im.url }}">
                {% endthumbnail %}
              {% else %}
                  <img alt="" src="{% static 'img/default/product.jpg' %}" width="100%" class="frame2">
              {% endif %}
            <!---->
            <div class="card-body">
              <a href="{% url 'shop:product' product.id %}" class="stretched-link"></a>
              <h5 class="card-title">{{ product.name }}</h5>
              <hr class="hr-dashed-gradient"></hr>
              <div class="col" style="z-index:2; position: relative;">
                <h6 class="card-title">Магазин: <a href="{% url 'shop:shop' product.shop.id %}" class="custom-link">{{ product.shop.name }}</a></h6>
                <h6 class="card-title">Продавец: <a href="{% url 'users:user_profile' product.shop.owner.username %}" class="custom-link">{{ product.shop.owner.username }}</a></h6>
              </div>
              {% if product.avg_rating %}
                <p>Рейтинг товара: {{ product.avg_rating|floatformat:"0" }}/5⭐</p>
              {% else %}
                <p>Рейтинг товара: отзывов нет</p>
              {% endif %}
                <p><b>Цена: {{product.price }} ₽</b></p>
              <div class="row row-cols-auto">
                {% for category in product.category.all %}
                  <div class="col" style="z-index:2; position: relative;">
                    <a href="{% url 'shop:category' category.slug %}" class="btn btn-light btn-custom-category" style="font-size:12px">
                      {{ category.name }}
                    </a>
                  </div>
                {% endfor %}
              </div>
              <div class="row">
                <div class="col">
                  <p class="card-text">Описание: {{ product.description }}</p>
                </div>
                <div class="col text-end">
                  <small class="text-muted">{{ product.created_date }}</small>
                </div>
              </div>
              {% if product.shop.owner != request.user and request.user.is_authenticated and request.resolver_match.view_name != 'moderation:moderation_product' %}
                <hr class="hr-dashed-gradient"></hr>
                <div style="z-index:2; position: relative;">
                  <div class="btn-group justify-content-start">
                    {% if product.is_available %}
                      <form action="{% url 'cart:add_to_cart' %}" method="POST" class="add-to-cart-form" id="{{ product.id }}">
                        {% csrf_token %}
                        {% if product.in_cart %}
                          <button style="position: relative" type="submit" class="btn btn-success btn-sm me-1 mb-2" data-mdb-toggle="tooltip" title="В корзине">
                            <i class="fa-solid fa-basket-shopping"></i>
                          </button>
                        {% else %}
                          <button style="position: relative" type="submit" class="btn btn-outline-success btn-sm me-1 mb-2" data-mdb-toggle="tooltip" title="В корзину">
                            <i class="fa-solid fa-basket-shopping"></i>
                          </button>
                        {% endif %}
                      </form>
                    {% else %}
                      <div class="text-center" style="margin-right:10px">
                        <div>
                          <h5>Нет в наличии</h5>
                        </div>
                        {% comment %} <div>
                          <a href="">
                            <span >сообщить о появлении</span>
                          </a>
                        </div> {% endcomment %}
                      </div>
                    {% endif %}
                      <form action="{% url 'users:change_favorite' %}" method="POST" class="favorite-form" id="{{ product.id }}">
                        {% csrf_token %}
                        <div class="favorite-btn-wrap">
                          {% if product.is_favorite %}
                            <button style="position: relative" type="submit" class="btn btn-danger btn-sm me-1 mb-2" data-mdb-toggle="tooltip" title="В избранном">
                              <i class="fa-solid fa-heart"></i>
                            </button>
                          {% else %}
                            <button style="position: relative" type="submit" class="btn btn-outline-danger btn-sm me-1 mb-2" data-mdb-toggle="tooltip" title="В избранное">
                              <i class="fa-regular fa-heart"></i>
                            </button>
                          {% endif %}
                        </div>
                      </form>
                  </div>
                </div>
              {% else %}
              <hr class="hr-dashed-gradient"></hr>
              {% endif %}
              {% if request.resolver_match.view_name == 'moderation:moderation_product' %}
                <div class="row text-center" style="z-index:2; position: relative;">
                  <div class="col">
                    <form method="POST" action="{% url 'moderation:accept_product' product.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-outline-success">
                        Одобрить
                      </button>
                    </form>
                  </div>
                  <div class="col">
                    <a href="{% url 'moderation:reject_product' product.id %}" class="btn btn-outline-danger">Отклонить</a>
                  </div>
                </div>
              {% else %}
              <!--Плашка для владельца магазина-->
                {% if product.shop.owner == request.user %}
                  <div>
                    <h5>Информация для владельца:</h3>
                      {% if product.visibile == True %}
                        <p class="accept">Видимость товара: {{ product.visibile }}
                          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
                        </p>
                      {% else %}
                        <p class="reject">Видимость товара: <i class="fa-sharp fa-solid fa-circle"></i>{{ product.visibile }}
                          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
                        </p>
                      {% endif %}
                      {% if product.status == 'Accept' %}
                        <p class="accept">Статус товара: {{ product.get_status_display }}
                          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
                        </p>
                      {% elif product.status == 'Reject' %}
                        <p class="reject">Статус товара: {{ product.get_status_display }}
                          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
                        </p>
        
                          <p>Причина: {{ product.moderation.first.reason }}</p>

                      {% else %}
                        <p class="in_consideration">Статус товара: {{ product.get_status_display }}
                          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
                        </p>
                      {% endif %}
                    </div>
                  <!---->
                  <div class="btn-group" style="z-index:2; position: relative;">
                    <a href="{% url 'shop:create_item' product.id %}" class="btn btn-sm btn-outline-secondary">Добавить товар</a>
                    <form method="POST" action="{% url 'shop:delete_product' product.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-sm btn-outline-secondary">Удалить продукт</button>
                    </form>
                    <a href="{% url 'shop:edit_product' product.shop.id product.id %}" class="btn btn-sm btn-outline-secondary">Изменить продукт</a>
                  </div>
                {% endif %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
{% comment %} </div> {% endcomment %}

digital_store/templates/includes/footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
  {% with request.resolver_match.view_name as view_name %}
  <li><a href="{% url 'shop:index' %}" class="nav-link px-2 {% if view_name == 'shop:index' %}link-secondary{% else %}link-dark{% endif %}">Главная</a></li>
  <li><a href="{% url 'shop:shop_list' %}" class="nav-link px-2 {% if view_name == 'shop:shop_list' %}link-secondary{% else %}link-dark{% endif %}">Магазины</a></li>
  <li><a href="{% url 'shop:product_list' %}" class="nav-link px-2 {% if view_name == 'shop:product_list' %}link-secondary{% else %}link-dark{% endif %}">Товары</a></li>
  {% if user_have_shop %}
    <li><a href="{% url 'users:shops' request.user.username %}" class="nav-link px-2 {% if view_name == 'shop:user_shops' %}link-secondary{% else %}link-dark{% endif %}">Мои магазины</a></li>
  {% else %}
    <li><a href="{% url 'shop:create_shop' %}" class="nav-link px-2 {% if view_name == 'shop:create_shop' %}link-secondary{% else %}link-dark{% endif %}">Открыть магазин</a></li>
  {% endif %}
  {% endwith %}
</ul>
<p class="text-center text-muted">© {{ year }} Digital Marketplace</p>

digital_store/templates/includes/header.html
{% load thumbnail %}
{% load static %}
<div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'shop:index' %}" class="nav-link px-2 {% if view_name == 'shop:index' %}link-secondary{% else %}link-dark{% endif %}">Главная</a></li>
        <li><a href="{% url 'shop:shop_list' %}" class="nav-link px-2 {% if view_name == 'shop:shop_list' %}link-secondary{% else %}link-dark{% endif %}">Магазины</a></li>
        <li><a href="{% url 'shop:product_list' %}" class="nav-link px-2 {% if view_name == 'shop:product_list' %}link-secondary{% else %}link-dark{% endif %}">Товары</a></li>
        {% if user_have_shop %}
          <li><a href="{% url 'users:shops' request.user.username %}" class="nav-link px-2 {% if view_name == 'users:shops' and request.resolver_match.kwargs.username == request.user.username %}link-secondary{% else %}link-dark{% endif %}">Мои магазины</a></li>
        {% else %}
          <li><a href="{% url 'shop:create_shop' %}" class="nav-link px-2 {% if view_name == 'shop:create_shop' %}link-secondary{% else %}link-dark{% endif %}">Открыть магазин</a></li>
        {% endif %}
        {% if is_staff %}
        <div class="dropdown">
          <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Уголок модератора
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'moderation:moderation_shop' %}">Магазины</a></li>
            <li><a class="dropdown-item" href="{% url 'moderation:moderation_product' %}">Продукты</a></li>
            <li><a class="dropdown-item" href="{% url 'moderation:moderation_history' %}">История</a></li>
          </ul>
        </div>
        {% endif %}
    </ul>
    {% endwith %}

    <form action="{% url 'shop:search' %}" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input name="query" type="search" class="form-control" placeholder="Поиск..." aria-label="Поиск">
    </form>
    
    {% if request.user.is_authenticated %}
      <div style="margin-left:10px; margin-right:20px;">
        <a class="a-cart" href="{% url 'cart:cart' %}">
          <i class="fa-solid fa-cart-shopping fa-xl" style="color: #1162ee;"></i>
          {% if count_products_cart %}
            <span class="position-absolute translate-middle badge rounded-pill bg-danger count-cart-items">{{ count_products_cart }}</span>
          {% endif %}
        </a>
      </div>
      <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          {% if request.user.image %}
            {% thumbnail request.user.image "32x32" crop="center" as im %}
              <img src="{{ im.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
            {% endthumbnail %}
          {% else %}
            <img src="{% static 'img/default/user.webp' %}" alt="mdo" width="32" height="32" class="rounded-circle">
          {% endif %}
          </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser" style="">
            <li><a class="dropdown-item" href="{% url 'users:user_profile' request.user.username %}">Профиль</a></li>
            <li><a class="dropdown-item" href="{% url 'users:favorites' %}">Избранное</a></li>
            <li><a class="dropdown-item" href="{% url 'users:orders' %}">Список покупок</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
          </ul>
      </div>
    {% else %}
      <div class="col-md-3 text-end">
        <a href="{% url "users:login" %}" class="btn btn-outline-primary me-2">Войти</a>
        <a href="{% url "users:signup" %}" class="btn btn-primary">Регистрация</a>
      </div>
    {% endif %}
    </div>
</div>

digital_store/templates/includes/item_in_cart.html
{% load thumbnail %}
{% load static %}
{% load custom_filters %}
<!-- Single item -->
<div class="row" id="card-{{ obj.product.id }}">
  <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
    <!--Изображение товара-->
    {% if obj.product.image %}
      {% thumbnail obj.product.image "410x320" crop="center" as im %}
        <img class="card-img top" src="{{ im.url }}">
      {% endthumbnail %}
    {% else %}
      <img alt="" src="{% static 'img/default/product.jpg' %}" width="100%" class="frame2">
    {% endif %}
    <!---->
  </div>

  <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
    <!-- Data -->
    <p><strong>Название: <a href="{% url 'shop:product' obj.product.id %}" style="text-decoration: none; color:black">{{ obj.product.name }}</strong></p></a>
    <p>Магазин: {{ obj.product.shop.name }}</p>
    <p>Цена за штуку: {{ obj.product.price }} ₽</p>
    <div>
      <form action="{% url 'cart:remove_count_items'%}" method="POST" class="remove-count-form" id="{{ obj.id }}">
        {% csrf_token %}
        {% if obj.count_items == False %}
          <button class="btn remove-count-btn{{ obj.id }}" disabled=""><i class="fa-solid fa-minus"></i></button>
        {% else %}
          <button class="btn remove-count-btn{{ obj.id }}"><i class="fa-solid fa-minus"></i></button>
        {% endif %}
      </form>
      {% if obj.product.count != 0 %}
        <p style="display:inline">Количество: <p style="display:inline" class="count-items{{ obj.id }}">{{ obj.count_items }}</p> шт.
      {% else %}
        <p style="display:inline; color:#B22222;">Нет в наличии
      {% endif %}
      <form action="{% url 'cart:add_count_items'%}" method="POST" class="add-count-form" id="{{ obj.id }}">
        {% csrf_token %}
        {% if obj.count_items == obj.product.count %}
          <button class="btn add-count-btn{{ obj.id }}" id="add-count-btn" disabled=""><i class="fa-solid fa-plus"></i></button>
        {% else%}
          <button class="btn add-count-btn{{ obj.id }}" id="add-count-btn"><i class="fa-solid fa-plus"></i></button>
        {% endif %}
      </form>
      </p>
    </div>
    <form action="{% url 'cart:del_from_cart' %}" method="POST" class="del-from-cart-form" id="{{ obj.product.id }}">
      {% csrf_token %}
      <button class="btn btn-primary btn-sm me-1 mb-2" id="del-from-cart-btn"><i class="fas fa-trash"></i></button>
    </form>
  </div>

  <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
    <!-- Price -->
    <h4 class="text-start text-md-center">Цена</h3>
    <p class="text-start text-md-center">
      <strong class="full-price{{ obj.id }}">{{ obj|get_product_full_price }}</strong> <strong>₽</strong>
    </p>
    <!-- Price -->
  </div>
  <hr class="hr-dashed-gradient"></hr>
</div>
<!-- Single item -->

digital_store/templates/includes/shop_card.html
{% load thumbnail %}
{% load static %}
<div class="card" style="padding:0;">
    {% if shop.image %}
      {% thumbnail shop.image "500x250" crop="center" upscale=TRUE as im %}
        <img class="shop-img" src="{{ im.url }}">
      {% endthumbnail %}
    {% else %}
      <img class="shop-img-default" src="{% static 'img/default/shop.webp' %}">
    {% endif %}
  <div class="card-body">
    <h3 class="card-title">{{ shop.name }}</h3>
    <hr class="hr-dashed-gradient"></hr>
    <p class="card-text">Владелец: <a href="{% url 'users:user_profile' shop.owner.username %}" class="custom-link">{{ shop.owner.username }}</a></p>
    {% if shop.avg_rating %}
      <p>Рейтинг магазина: {{ shop.avg_rating|floatformat:"0" }}/5⭐</p>
    {% else %}
      <p>Рейтинг магазина: отзывов нет</p>
    {% endif %}
    <p class="card-text">Описание: {{ shop.description }}</p>
    {% if request.resolver_match.view_name == 'shop:user_shops' %}
      {% if shop.status == 'Accept' %}
        <h5 class="accept">Статус магазина: {{ shop.get_status_display }}
          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
        </h5>
      {% elif shop.status == 'Reject' %}
        <h5 class="reject">Статус магазина: {{ shop.get_status_display }}
          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
        </h5>
      {% else %}
        <h5 class="in_consideration">Статус магазина: {{ shop.get_status_display }}
          <i class="fa-sharp fa-solid fa-circle fa-2xs"></i>
        </h5>
      {% endif %}
    {% endif %}
    <hr></hr>
    <div class="container text-center">
      {% if request.resolver_match.view_name == 'moderation:moderation_shop' %}
        <div class="row">
          <div class="col">
          <form method="POST" action="{% url 'moderation:accept_shop' shop.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success">
              Одобрить
            </button>
          </form>
          </div>
          <div class="col">
          <form method="POST" action="{% url 'moderation:reject_shop' shop.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">
              Отклонить
            </button>
          </form>
          </div>
        </div>
      {% else %}
        <a href="{% url 'shop:shop' shop.pk %}" class="btn btn-outline-secondary">Перейти в магазин</a>
        {% if request.user == shop.owner %}
          <a href="{% url 'shop:edit_shop' shop.pk %}" class="btn btn-outline-secondary">Редактировать магазин</a>
          <form method="POST" action="{% url 'shop:delete_shop' shop.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-secondary">
              Удалить магазин
            </button>
          </form>
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>
  