digital_store/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/', views.add_to_cart,
         name='add_to_cart'),
    path('del_from_cart/', views.del_from_cart,
         name='del_from_cart'),
    path('make_order/', views.make_order, name='make_order'),
    path('add_count_items/', views.add_count_items,
         name='add_count_items'),
    path('remove_count_items/', views.remove_count_items,
         name='remove_count_items'),
    path('', views.cart, name='cart'),
]

digital_store/digital_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('moderation/', include('moderation.urls')),
    path('review/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]


handler404 = 'core.views.page_not_found'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

digital_store/moderation/urls.py
from django.urls import path

from . import views

app_name = 'moderation'

urlpatterns = [
     path('shops/', views.moderation_shop, name='moderation_shop'),
     path('accept_shop/<int:shop_id>/', views.accept_shop, name='accept_shop'),
     path('reject_shop/<int:shop_id>/', views.reject_shop, name='reject_shop'),
     path('products/', views.moderation_product, name='moderation_product'),
     path('accept_product/<int:product_id>/', views.accept_product,
          name='accept_product'),
     path('reject_product/<int:product_id>/', views.reject_product,
          name='reject_product'),
     path('moderation_history/', views.moderation_history,
          name='moderation_history'),
     path('change_moderator_status/', views.change_moderator_status,
          name='change_moderator_status'),
]

digital_store/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('favorites/', views.get_favorite_list, name='favorites'),
    path('change_favorite/', views.change_favorite, name='change_favorite'),
    path('profile/<slug:username>/', views.user_profile, name='user_profile'),
    path('orders/', views.order_list, name='orders'),
    path('shops/<slug:username>/', views.get_user_shop_list, name='shops'),
    path('products/<slug:username>', views.get_user_product_list,
         name='products'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

digital_store/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USER_ROLE = (
        ('user', 'Пользователь'),
        ('moderator', 'Модератор'),
        ('admin', 'Администратор'),
    )

    role = models.CharField(
        verbose_name='Роль',
        max_length=32,
        choices=USER_ROLE,
        default='user',
    )

    image = models.ImageField(
        default=None,
        upload_to='users/profile_img/',
        verbose_name='Изображение профиля',
        blank=True,
    )

    @property
    def is_moderator(self):
        return self.role == 'moderator'

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Favorite(models.Model):
    """
    Модель избранного
    """

    user = models.ForeignKey(
        User,
        related_name='favorite',
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
    )

    product = models.ForeignKey(
        'shop.Product',
        related_name='favorite',
        on_delete=models.CASCADE,
        verbose_name='Продукт',
    )

    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата добавления',
    )

    def __str__(self):
        return f'{self.user} <3 {self.product}'

    class Meta:
        constraints = [models.UniqueConstraint(fields=('user', 'product'),
                       name='Уникальные значения')]
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранное'

digital_store/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email')


class ChangeProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image')

digital_store/users/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.db.models import Avg, BooleanField, Case, Count, When
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from cart.models import Order, OrderHistory
from core.actions import is_ajax
from core.pagination import get_context_paginator
from reviews.models import Review
from shop.models import Product, Shop
from shop.views import get_products

from .forms import ChangeProfileForm, CreationForm
from .models import Favorite, User


def _get_percent_rating(user) -> dict:
    """
    Получение процента по шкале рейтинга
    """

    stars_dict = {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
    }

    stars_percent = {
        1: (0, 0),
        2: (0, 0),
        3: (0, 0),
        4: (0, 0),
        5: (0, 0),
    }

    reviews = Review.objects.filter(product__shop__owner=user).values('rating')

    if reviews.count() == 0:
        return stars_percent

    # заполняем словарь для подсчета каждой оценки
    for star in reviews:
        stars_dict[star['rating']] += 1

    # заполняем словарь для подсчета процента по оценкам
    for star in stars_dict:
        stars_percent[star] = (
            stars_dict[star], round((stars_dict[star] / reviews.count()) * 100)
        )
    return stars_percent


############################
class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('shop:index')
    template_name = 'users/signup.html'


def user_profile(request, username):
    """
    Профиль пользователя
    """

    user = get_object_or_404(User, username=username)
    context = {
        'user': user,
        }
    if Shop.objects.filter(owner=user).exists():
        count_shops = Shop.objects.filter(owner=user, status='Accept').count()
        count_products = Product.objects.filter(
            shop__owner=user,
            status='Accept',
            is_available=True,
            visibile=True
        ).count()

        rating = (Review.objects
                  .filter(product__shop__owner=user)
                  .aggregate(Avg('rating'))
                  )

        rating = (int(rating.get('rating__avg'))
                  if (rating.get('rating__avg')) is not None else None)

        count_sales = (OrderHistory.objects
                       .filter(product__shop__owner=user)
                       .aggregate(Count('count_items'))
                       )

        context.update({
            'count_shops': count_shops,
            'count_products': count_products,
            'rating': rating,
            'count_sales': count_sales.get('count_items__count'),
            'percent_rating': _get_percent_rating(user),
        })
    return render(request, context=context, template_name='users/profile.html')


@login_required
def order_list(request):
    """
    Отображение списка покупок для юзера
    """

    orders = (Order.objects
              .filter(order_history__user=request.user)
              .distinct()
              .prefetch_related('order_history__product__shop',
                                'order_history__items')
              .order_by('-created_date')
              )

    context = {}

    context.update(get_context_paginator(orders, request))

    return render(request, context=context, template_name='users/orders.html')


@login_required
def get_favorite_list(request):
    """
    Получить список избранных продуктов
    """

    favorite_products = (Product.objects
                         .filter(favorite__user=request.user)
                         .prefetch_related('category')
                         .select_related('shop__owner')
                         .annotate(avg_rating=Avg('review__rating'),
                                   is_favorite=Case(
                                        When(favorite__user=request.user,
                                             then=True),
                                        default=False,
                                        output_field=BooleanField()),
                                   in_cart=Case(
                                        When(cart__user=request.user,
                                             then=True),
                                        default=False,
                                        output_field=BooleanField(),
                                        )))

    context = {}

    context.update(get_context_paginator(favorite_products, request))

    return render(request, context=context,
                  template_name='users/favorites.html')


@login_required
def change_favorite(request):
    """
    Удаление/добавление продукта из избранного
    """

    if is_ajax(request=request) and request.method == 'POST':
        data = request.POST
        is_favorite = False
        product = get_object_or_404(Product, id=int(data['product_id']))
        fav_obj = Favorite.objects.filter(user=request.user, product=product)
        if fav_obj.exists():
            fav_obj.first().delete()
        else:
            Favorite.objects.create(user=request.user, product=product)
            is_favorite = True

        context = {
            'is_favorite': is_favorite,
        }

        cache.clear()
        return JsonResponse(context, status=200)
    return JsonResponse({"success": False}, status=400)


def get_user_shop_list(request, username):
    """
    Получаем все магазины данного юзера
    """
    user = get_object_or_404(User, username=username)
    if request.user == user:
        shops = (Shop.objects
                 .filter(owner=user)
                 .select_related('owner')
                 )
    else:
        shops = Shop.objects.filter(owner=user,
                                    status='Accept').select_related('owner')

    context = {}
    context.update(get_context_paginator(shops, request))
    return render(request, context=context,
                  template_name='shop/shop_list.html')


def get_user_product_list(request, username):
    """
    Получаем все товары(продукты) связанные с данным юзером
    """
    user = get_object_or_404(User, username=username)
    if request.user == user:
        products = get_products(request)
        products = products.filter(shop__owner=user)
    else:
        products = get_products(request)
        products = products.filter(shop__owner=user,
                                   visibile=True, status='Accept')
    context = {}
    context.update(get_context_paginator(products, request, is_products=True))
    return render(request, context=context,
                  template_name='shop/product_list.html')


def edit_profile(request):
    user = request.user
    form = ChangeProfileForm(request.POST or None,
                             files=request.FILES or None,
                             instance=user)
    if form.is_valid():
        form.save()
        return redirect('users:user_profile', user.username)

    context = {
        'form': form,
    }
    return render(request, context=context,
                  template_name='users/edit_profile.html')

digital_store/templates/users/edit_profile.html
{% extends 'base.html' %}
{% block title %}
Редактировать профиль
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
          <div class="card-header">     
            Редактировать профиль
          </div>
        <div class="card-body">  
          <form method="post" enctype="multipart/form-data" action="{% url 'users:edit_profile' %}">
            {% csrf_token %}
              {% for field in form %}           
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}                  
                      <span class="required text-danger" >*</span>
                    {% endif %}                  
                  </label>
                  {{ field }}
                  {% if field.help_text %}             
                    <small id="id_text-help" class="form-text text-muted">
                      {{ field.help_text }}
                    </small>
                  {% endif %}                  
                </div>
              {% endfor %}            
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Сохранить
                </button>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

digital_store/templates/users/favorites.html
{% extends 'base.html' %}
{% block title %} Избранные товары {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Digital Marketplace</h1>
          <p class="lead text-muted">Список ваших избранных товаров. </p>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    <div class="album py-3 bg-white">
      <section class="py-5 text-center container">
        {% if page_obj %}
          <h2>Товары</h2>
        {% else %}
          <h2>Ни одного товара нет.</h2>
        {% endif %}
      </section>
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for product in page_obj %}
            {% include 'includes/card.html' %}
          {% endfor %}
        </div>
        <div class="d-flex align-items-center justify-content-center">
          {% include 'includes/paginator.html'%}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

digital_store/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Вы не авторизованы
        </div>
        <div class="card-body">
          <p style="text-align: center;">
            Вы не вошли в свой аккаунт.
          </p>
          <div style="width: 10%; margin: auto;">
            <a href="">
              <button class="btn btn-dark">
                Войти
              </button>
            </a>
          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %} 

digital_store/templates/users/login.html
{% extends 'base.html' %}
{% block title %} Авторизация {% endblock title %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5" style="">
      <div class="card" style="width:60%; margin:auto">
        {% if user.is_authenticated %}
          <div class="card-header">
            Вы уже авторизованы
          </div>
          <div class="card-body">
            <p style="text-align: center;">
              Вы уже авторизованы.
            </p>
            <div style="width: 10%; margin: auto;">
              <a href="{% url 'users:logout' %}">
                <button class="btn btn-dark">
                  Выйти
                </button>
              </a>
            </div>
          </div>
        {% else %}
          <div class="card-header">
            Войти на сайт
          </div>
          <div class="card-body">
            {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}

            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                <div>
                {{ field }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-5">
              <button type="submit" class="btn btn-dark">
                Войти
              </button>
            </div>
            </form>
          </div> <!-- card body -->
        {% endif %}
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

digital_store/templates/users/orders.html
{% extends 'base.html' %}
{% block title %} История покупок {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Digital Marketplace</h1>
          <p class="lead text-muted">Это твоя история покупок</p>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    {% for order in page_obj %}
      {% include 'includes/order.html '%}
    {% endfor %}
    <div class="d-flex align-items-center justify-content-center">
      {% include 'includes/paginator.html'%}
    </div>
  </main>
{% endblock content %}

digital_store/templates/users/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} Страница профиля {% endblock title %}
{% block content %}
<section style="background-color: #eee;">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            {% if user.image %}
            {% thumbnail user.image "150x150" crop="center" as im %}
              <img src="{{ im.url }}" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
            {% endthumbnail %}
            {% else %}
              <img src="{% static 'img/default/user.webp' %}" class="rounded-circle img-fluid" style="width: 150px;">
            {% endif %}
            <h5 class="my-3">{{ user.username }}</h5>
            <div class="d-flex justify-content-center mb-2">
              {% if request.user.role == 'admin' and request.user != user and user.role != 'admin' %}
              <form action="{% url 'moderation:change_moderator_status' %}" method="POST" class="make-remove-form" id="{{ user.id }}">  
              {% csrf_token %}
                  {% if user.role == 'moderator' %}
                    <button type="submit" class="btn btn-outline-danger">Убрать из модераторов</button>
                  {% else %}
                    <button type="submit" class="btn btn-outline-success">Сделать модератором</button>
                  {% endif %}
                {% elif request.user == user %}
                  <a href="{% url 'users:edit_profile' %}" class="btn btn-outline-primary ms-1">Редактировать</a>
                {% endif %}
              </form>
            </div>
          </div>
        </div>
        {% if count_shops %}
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <h4 class="text-center" style="margin-top:20px">Статус: Продавец <i class="fa-solid fa-check fa-fade" style="color: #18aa0e;"></i></h4>
            <ul class="list-group list-group-flush rounded-3">
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <div class="container">
                  <div class="row">
                    <div class="col-8">
                      <a href="{% url 'users:shops' user.username %}" class="custom-link-profile">
                      <i class="fa-solid fa-shop" style="color: #403f3f;"> Магазинов:</i>
                      </a>
                    </div>
                    <div class="col">
                      <p class="mb-0">{{ count_shops }}</p>
                    </div>
                  </div>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <div class="container">
                  <div class="row">
                    <div class="col-8">
                      <a href="{% url 'users:products' user.username %}" class="custom-link-profile">
                      <i class="fa-solid fa-box" style="color: #403f3f;"> Товаров (в наличии):</i>
                      </a>
                    </div>
                    <div class="col">
                      <p class="mb-0">{{ count_products }}</p>
                    </div>
                  </div>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <div class="container">
                  <div class="row">
                    <div class="col-8">
                      <i class="fa-solid fa-cart-arrow-down" style="color: #403f3f;"> Количество продаж:</i>
                    </div>
                    <div class="col">
                      <p class="mb-0">{{ count_sales }}</p>
                    </div>
                  </div>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <div class="container">
                  <div class="row">
                    <div class="col-8">
                      <i class="fa-solid fa-star-half-stroke" style="color: #403f3f;"> Рейтинг продавца: </i>
                      </a>
                    </div>
                    <div class="col">
                      {% if rating %}
                        <p class="mb-0">{{ rating }}/5⭐</p>
                      {% else %}
                        <p class="mb-0">Отзывов нет</p>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Имя</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{% if user.first_name %}{{ user.first_name }}{% else %}не указано{% endif %}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Фамилия</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{% if user.last_name %}{{ user.last_name }}{% else %}не указано{% endif %}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Дата регистрации</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ user.date_joined|date }}</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="text-center mb-4"><span class="text-primary font-italic me-1">Подробный рейтинг</span>
                </p>
                <p class="text-center mb-1" style="font-size: .77rem;">5 ⭐ (оценок: {{ percent_rating.5.0 }})</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: {{ percent_rating.5.1 }}%" aria-valuenow="80"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="text-center mt-4 mb-1" style="font-size: .77rem;">4 ⭐ (оценок: {{ percent_rating.4.0 }})</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: {{ percent_rating.4.1 }}%" aria-valuenow="72"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="text-center mt-4 mb-1" style="font-size: .77rem;">3 ⭐ (оценок: {{ percent_rating.3.0 }})</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: {{ percent_rating.3.1 }}%" aria-valuenow="89"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="text-center mt-4 mb-1" style="font-size: .77rem;">2 ⭐ (оценок: {{ percent_rating.2.0 }})</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: {{ percent_rating.2.1 }}%" aria-valuenow="55"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="text-center mt-4 mb-1" style="font-size: .77rem;">1 ⭐ (оценок: {{ percent_rating.1.0 }})</p>
                <div class="progress rounded mb-2" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: {{ percent_rating.1.1 }}%" aria-valuenow="66"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

digital_store/templates/users/signup.html
{% extends 'base.html' %}
{% block title %} Регистрация {% endblock title %}
{% block content %}
  <div class="row justify-content-center">
    <div class='register'>
      <div class="col-md-8 p-5" style="margin:auto">
        <div class="card">
          {% if user.is_authenticated %}
          <div class="card-header">
            Вы уже зарегистрированы
          </div>
          <div class="card-body">
            <p style="text-align: center;">
              Вы уже зарегистрированы. Выйдите из аккаунта для регистрации нового.
            </p>
            <div style="width: 10%; margin: auto;">
              <a href="{% url 'users:logout' %}">
                <button class="btn btn-dark">
                  Выйти
                </button>
              </a>
            </div>
          </div>
        {% else %}
          <div class="card-header">
            Зарегистрироваться
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>    
                  {{ field }} 
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-dark">
                    Зарегистрироваться
                  </button>
                </div>
              </form>
            </div> <!-- card body -->
            {% endif %}
          </div> <!-- card -->
        </div> <!-- col -->
      </div>
  </div> <!-- row -->
{% endblock %}