digital_store/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/', views.add_to_cart,
         name='add_to_cart'),
    path('del_from_cart/', views.del_from_cart,
         name='del_from_cart'),
    path('make_order/', views.make_order, name='make_order'),
    path('add_count_items/', views.add_count_items,
         name='add_count_items'),
    path('remove_count_items/', views.remove_count_items,
         name='remove_count_items'),
    path('', views.cart, name='cart'),
]

digital_store/digital_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('moderation/', include('moderation.urls')),
    path('review/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]


handler404 = 'core.views.page_not_found'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

digital_store/reviews/urls.py
from django.urls import path

from . import views

app_name = 'review'

urlpatterns = [
    path('add/product/<int:product_id>/', views.review_add, name='review_add'),
    path('shop/<int:shop_id>/', views.reviews_shop_list,
         name='reviews_shop_list'),
]

digital_store/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/<int:shop_id>/', views.shop, name='shop'),
    path('product/<int:product_id>/', views.product, name='product'),
    path('create_shop/', views.create_shop, name='create_shop'),
    path('edit_shop/<int:shop_id>/', views.edit_shop, name='edit_shop'),
    path('delete_shop/<int:shop_id>/', views.delete_shop, name='delete_shop'),
    path('shop/<int:shop_id>/create_product/', views.create_product,
         name='create_product'),
    path('shop/<int:shop_id>/edit_product/<int:product_id>/',
         views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product,
         name='delete_product'),
    path('product/<int:product_id>/create_item/', views.create_item,
         name='create_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('shops/', views.shop_list, name='shop_list'),
    path('products/', views.product_list, name='product_list'),
    path('search/', views.search, name='search'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('', views.index, name='index'),
]

digital_store/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('favorites/', views.get_favorite_list, name='favorites'),
    path('change_favorite/', views.change_favorite, name='change_favorite'),
    path('profile/<slug:username>/', views.user_profile, name='user_profile'),
    path('orders/', views.order_list, name='orders'),
    path('shops/<slug:username>/', views.get_user_shop_list, name='shops'),
    path('products/<slug:username>', views.get_user_product_list,
         name='products'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

digital_store/shop/forms.py
from django import forms

from .models import Item, Product, Shop


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        widgets = {
            'description': forms.Textarea,
        }
        fields = ('name', 'image', 'description')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'price', 'category', 'image', 'description',
                  'visibile')


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        widgets = {
            'item': forms.Textarea,
        }
        fields = ('item',)

digital_store/shop/views.py
from functools import wraps

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, BooleanField, Case, When
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_POST

from cart.models import OrderHistory
from core.pagination import get_context_paginator
from digital_store.settings import CACHE_TIME, STAFF_ROLES
from moderation.models import AcceptRejectList
from reviews.forms import ReviewForm
from reviews.models import Review

from .forms import ItemForm, ProductForm, ShopForm
from .models import Category, Item, Product, Shop


def get_products(request):
    """
    Получение продуктов без фильтров
    """
    products = (Product.objects
                .filter()
                .select_related('shop__owner')
                .prefetch_related('category', 'review')
                .order_by('-is_available', '-created_date')
                .annotate(avg_rating=Avg('review__rating'))
                )
    if request.user.is_authenticated:
        products = products.annotate(is_favorite=Case(
                            When(favorite__user=request.user,
                                 then=True),
                            default=False,
                            output_field=BooleanField()),
                          in_cart=Case(
                              When(cart__user=request.user,
                                   then=True),
                              default=False,
                              output_field=BooleanField(),
                      ))

    return products


def owner_required(func):
    """
    Декоратор. Проверка является ли юзер владельцем магазина
    """

    @wraps(func)
    def wrapper(request, *args, **kwargs):
        if 'shop_id' in kwargs:
            if request.user.is_authenticated:
                shop = get_object_or_404(Shop, id=kwargs.get('shop_id'))
                if request.user == shop.owner:
                    return func(request, *args, **kwargs)
        elif 'product_id' in kwargs:
            if request.user.is_authenticated:
                product = get_object_or_404(Product,
                                            id=kwargs.get('product_id'))
                if request.user == product.shop.owner:
                    return func(request, *args, **kwargs)
        elif 'item_id' in kwargs:
            if request.user.is_authenticated:
                item = get_object_or_404(Item, id=kwargs.get('item_id'))
                if request.user == item.product.shop.owner:
                    return func(request, *args, **kwargs)
        return redirect('shop:index')
    return wrapper


###############################################################


@cache_page(CACHE_TIME)
def index(request):
    """
    Главная страница проекта
    """

    products = (get_products(request)
                .filter(status='Accept', visibile=True)
                )

    context = {
        'products': products,
    }

    return render(
        request,
        context=context,
        template_name='shop/index.html'
    )


def shop(request, shop_id):
    """
    Страница магазина
    """

    shop = get_object_or_404(
        (Shop.objects
         .annotate(avg_rating=Avg('products__review__rating'))
         .select_related('owner')),
        id=shop_id)

    # проверка статуса магазина
    if shop.status != 'Accept':
        if request.user.is_authenticated is True:
            if (request.user != shop.owner or request.user.role
                    not in STAFF_ROLES):
                raise Http404
        else:
            raise Http404

    products = get_products(request)
    if not request.user.is_authenticated or request.user != shop.owner:
        products = products.filter(
                status='Accept',
                visibile=True,
                is_available=True
            )
    products = products.filter(shop=shop)

    context = {
        'shop': shop,
        'products': products,
        'products_exists': products.exists(),
    }

    context.update(get_context_paginator(products, request, is_products=True))

    return render(request, context=context, template_name='shop/shop.html')


@cache_page(CACHE_TIME)
def shop_list(request):
    """
    Страница со всеми магазинами
    """

    shops = (Shop.objects.filter(status='Accept')
             .select_related('owner')
             .annotate(avg_rating=Avg('products__review__rating'))
             .order_by('-created_date'))

    context = {
        'shops': shops,
    }

    context.update(get_context_paginator(shops, request))
    return render(
        request,
        context=context,
        template_name='shop/shop_list.html'
    )


def product(request, product_id):
    """
    Страница продукта
    """

    can_review = False

    if Product.objects.filter(pk=product_id).exists():

        product = (Product.objects
                   .filter(pk=product_id)
                   .select_related('shop__owner')
                   .annotate(
                        avg_rating=Avg('review__rating'),
                    ))
        if request.user.is_authenticated:
            product = product.annotate(is_favorite=Case(
                    When(favorite__user=request.user,
                         then=True),
                    default=False,
                    output_field=BooleanField()),
                in_cart=Case(
                    When(cart__user=request.user,
                         then=True),
                    default=False,
                    output_field=BooleanField()))
            can_review = OrderHistory.objects.filter(
                product=product.first(),
                user=request.user,
                review=False
            )
    else:
        raise Http404
    product = product.first()
    shop = Shop.objects.get(products=product_id)
    items = Item.objects.filter(product=product, status='sale')
    reviews = (Review.objects.filter(product=product)
               .select_related('user')
               .order_by('-created_date'))
    review_form = ReviewForm()

    if product.status != 'Accept':
        if request.user.is_authenticated is True:
            if (request.user != shop.owner or
                    request.user.role not in STAFF_ROLES):
                raise Http404
        else:
            raise Http404

    context = {
        'shop': shop,
        'product': product,
        'items': items,
        'reviews': reviews,
        'review_form': review_form,
        'items_exists': items.exists(),
        'can_review': can_review,
    }

    context.update(get_context_paginator(reviews, request))

    return render(
        request,
        context=context,
        template_name='shop/product.html'
    )


@cache_page(CACHE_TIME)
def product_list(request):
    """
    Страница со всеми продуктами
    """

    products = (get_products(request)
                .filter(status='Accept', visibile=True)
                )

    context = {}
    context.update(get_context_paginator(products, request, is_products=True))

    return render(
        request,
        context=context,
        template_name='shop/product_list.html'
    )


@login_required
def create_shop(request):
    """
    Сраница создания магазина
    """

    form = ShopForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        shop = form.save(commit=False)
        shop.owner = request.user
        shop.save()
        return redirect('shop:index')

    context = {
        'form': form,
    }
    return render(
        request,
        context=context,
        template_name='shop/create_shop.html'
    )


@owner_required
def edit_shop(request, shop_id):
    """
    Редактирование магазина
    """

    shop = get_object_or_404(Shop, pk=shop_id)
    form = ShopForm(request.POST or None,
                    files=request.FILES or None,
                    instance=shop)

    if form.is_valid():
        form.save()
        shop.status = 'In_Consideration'
        shop.save(delete=True)
        AcceptRejectList.objects.filter(shop=shop, product=None).delete()
        return redirect('shop:user_shops')
    context = {
        'edit_shop': True,
        'form': form,
        'shop_id': shop_id,
    }
    return render(
        request,
        context=context,
        template_name='shop/create_shop.html',
    )


@require_POST
@owner_required
def delete_shop(request, shop_id):
    """
    Удаление магазина юзером
    """

    shop = get_object_or_404(Shop, id=shop_id, owner=request.user)

    # удаляем все ордеры связаныне с данным магазином (с его продуктами)
    for pr in shop.products.all():
        for o_h in pr.order_history.all():
            o_h.order.delete()
    shop.delete()
    return redirect('shop:index')


@owner_required
def create_product(request, shop_id):
    """
    Создание подукта
    """

    form = ProductForm(request.POST or None,
                       files=request.FILES or None)

    shop = get_object_or_404(Shop, id=shop_id)

    if shop.status != 'Accept':
        messages.error(request, f'Вы не можете добавить товар. '
                                f'Ваш магазин имеет статус: '
                                f'{shop.get_status_display()}.')
        return redirect('shop:shop', shop_id)

    if form.is_valid():
        product = form.save(commit=False)
        product.shop = shop
        product.count = 0
        product.save()
        form.save_m2m()
        return redirect('shop:shop', shop_id)

    context = {
        'form': form,
        'shop': shop,
    }

    return render(
        request,
        context=context,
        template_name='shop/create_product.html'
    )


@owner_required
def edit_product(request, shop_id, product_id):
    """
    Редактирование продукта
    """

digital_store/templates/shop/category.html
{% extends 'base.html' %}
{% block title %} Категории {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Digital Marketplace</h1>
          <p class="lead text-muted">Результат по категории: {{ slug }}</p>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    <div class="album py-3 bg-white">
      <section class="py-5 text-center container">
        {% if page_obj %}
          <h2>Товары</h2>
        {% else %}
          <h2>Ни одного товара в данной категории нет.</h2>
          <h2>Открывай свой магазин и добавляй свои товары!</h2>
        {% endif %}
      </section>
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for product in page_obj %}
            {% include 'includes/card.html' %}
          {% endfor %}
        </div>
        <div class="d-flex align-items-center justify-content-center">
          {% include 'includes/paginator.html'%}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

digital_store/templates/shop/create_item.html
{% extends 'base.html' %}
{% block title %}
Добавить товар
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
          <div class="card-header"> 
            Новый товар          
          </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" action="{% url 'shop:create_item' product.id %}">
          {% csrf_token %}
            {% for field in form %}           
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}                  
                    <span class="required text-danger" >*</span>
                  {% endif %}                  
                </label>
                {{ field }}
                {% if field.help_text %}             
                  <small id="id_text-help" class="form-text text-muted">
                    {{ field.help_text }}
                  </small>
                {% endif %}                  
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if edit_product %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

digital_store/templates/shop/create_product.html
{% extends 'base.html' %}
{% block title %}
{% if edit_product %}
  Редактировать продукт
{% else %}
  Добавить продукт
{% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
          <div class="card-header"> 
            {% if edit_product %}      
              Редактировать продукт 
            {% else %}
              Новый продукт
            {% endif %}            
          </div>
        <div class="card-body">
          {% if edit_product %}   
            <form method="post" enctype="multipart/form-data" action="{% url 'shop:edit_product' product_id shop.id %}">
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'shop:create_product' shop.id %}">
          {% endif %}
          {% csrf_token %}
            {% for field in form %}           
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}                  
                    <span class="required text-danger" >*</span>
                  {% endif %}                  
                </label>
                {{ field }}
                {% if field.help_text %}             
                  <small id="id_text-help" class="form-text text-muted">
                    {{ field.help_text }}
                  </small>
                {% endif %}                  
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if edit_product %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

digital_store/templates/shop/create_shop.html
{% extends 'base.html' %}
{% block title %}
{% if edit_shop %}
  Редактировать магазин
{% else %}
  Создать магазин
{% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
          <div class="card-header"> 
            {% if edit_shop %}      
              Редактировать пост 
            {% else %}
              Новый магазин
            {% endif %}            
          </div>
        <div class="card-body">
          {% if edit_shop %}   
            <form method="post" enctype="multipart/form-data" action="{% url 'shop:edit_shop' shop_id %}">
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'shop:create_shop' %}">
          {% endif %}
            {% csrf_token %}
              {% for field in form %}           
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}                  
                      <span class="required text-danger" >*</span>
                    {% endif %}                  
                  </label>
                  {{ field }}
                  {% if field.help_text %}             
                    <small id="id_text-help" class="form-text text-muted">
                      {{ field.help_text }}
                    </small>
                  {% endif %}                  
                </div>
              {% endfor %}            
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if edit_shop %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

digital_store/templates/shop/index.html
{% extends 'base.html' %}
{% block title %} Главная страница {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Digital Marketplace</h1>
          <p class="lead text-muted">Хочешь купить? Купи у нас. Хочешь продать? Продай у нас.</p>
          <p>
            <a href="{% url 'shop:product_list' %}" class="btn btn-primary my-2">Список товаров</a>
            <a href="{% url 'shop:create_shop' %}" class="btn btn-secondary my-2">Открыть магазин</a>
          </p>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    <div class="album py-3 bg-white">
      <section class="py-5 text-center container">
        {% if products %}
          <h2>Последние добавленные товары</h2>
        {% else %}
          <h2>На данный момент товаров нет...</h2>
        {% endif %}
      </section>
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for product in products %}
            {% include 'includes/card.html' %}
          {% endfor %}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

digital_store/templates/shop/product.html
{% extends 'base.html' %}
{% block title %} Главная страница {% endblock title %}
{% block content %}
  <div class="container" style="width:700px">
    <div class="container content-center">
      {% include 'includes/card.html' %}
    </div>
    {% if request.user == product.shop.owner and items_exists %}
      <div class="container" style="margin-top:50px;width:600px">
        <h3>Ваши товары:</h3>
        <table id="table1" class="table table-bordered">
          <tbody>
            {% for item in items %}
              <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td id="description">{{ item.item }}</td>
                  <td>
                    <form method="POST" action="{% url 'shop:delete_item' item.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn">Удалить</button>
                    </form>
                  </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
    <div class="container" style="margin-top:50px;width:600px">
      <h3 class="text-center">Отзывы</h3>
      <p class="text-center"><i>(Количество: {{ product.review.count }})</i></p>
      {% for review in page_obj %}
        {% include 'includes/review.html' %}
        {% if forloop.last %}
        {% else %}
          <hr style="margin-top:10px"></hr>
        {% endif %}
      {% endfor %}
    </div>
    {% if can_review %}
      <a name="add-review"></a>
      <div>
        <form method="post" enctype="multipart/form-data" action="{% url 'review:review_add' product.id %}">
          {% csrf_token %}
            {% for field in review_form %}           
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}                  
                    <span class="required text-danger" >*</span>
                  {% endif %}                  
                </label>
                {{ field }}
                {% if field.help_text %}             
                  <small id="id_text-help" class="form-text text-muted">
                    {{ field.help_text }}
                  </small>
                {% endif %}                  
              </div>
            {% endfor %}            
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                  Добавить
              </button>
            </div>
        </form>
      </div>
    {% endif %}
    <div class="d-flex align-items-center justify-content-center">
      {% include 'includes/paginator.html'%}
    </div>
{% endblock %}

digital_store/templates/shop/product_list.html
{% extends 'base.html' %}
{% block title %} Страница продуктов {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Digital Marketplace</h1>
          <p class="lead text-muted">Еще нет магазина? Можешь открыть прямо сейчас, добавить свой товар и оказаться в этом списке!</p>
          <p>
            <a href="{% url 'shop:create_shop' %}" class="btn btn-secondary my-2">Открыть магазин</a>
          </p>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    <div class="album py-3 bg-white">
      <section class="py-5 text-center container">
        {% if page_obj %}
          <h2>Товары</h2>
        {% else %}
          <h2>Ни одного товара нет.</h2>
          <h2>Открывай свой магазин и добавляй свои товары!</h2>
        {% endif %}
      </section>
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for product in page_obj %}
            {% include 'includes/card.html' %}
          {% endfor %}
        </div>
        <div class="d-flex align-items-center justify-content-center">
          {% include 'includes/paginator.html'%}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

digital_store/templates/shop/shop.html
{% extends 'base.html' %}
{% block title %} Страница магазина {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Страница магазина <b>{{ shop.name }}</b></h1>
          <p>
            <a href="{% url 'users:user_profile' shop.owner.username %}" class="btn btn-primary my-2">Профиль продавца</a>
            <a href="{% url 'review:reviews_shop_list' shop.id %}" class="btn btn-secondary my-2">Посмотреть отзывы</a>
            {% if shop.owner == request.user %}
              <a href="{% url 'shop:create_product' shop.id %}" class="btn btn-secondary my-2">Добавить продукт</a>
              <a href="{% url 'shop:edit_shop' shop.pk %}" class="btn btn-secondary">Редактировать магазин</a>
            {% endif %}
            {% if shop.avg_rating %}
              <p>Рейтинг магазина: {{ shop.avg_rating|floatformat:"0" }}/5⭐</p>
            {% else %}
              <p>Рейтинг магазина: отзывов нет</p>
            {% endif %}
          </p>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    <div class="album py-3 bg-white">
      <section class="py-5 text-center container">
        <h2>Товары продавца</h2>
      </section>
      <div class="container">
        {% if products_exists %}
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in page_obj %}
              {% include 'includes/card.html' %}
            {% endfor %}
          </div>
          <div class="d-flex align-items-center justify-content-center">
            {% include 'includes/paginator.html'%}
          </div>
        {% else %}
          <section class="py-2 text-center container">
            <h4>На данный момент магазин пуст</h4>
            {% if shop.owner == request.user %}
              <a href="{% url 'shop:create_product' shop.id %}" class="btn btn-secondary my-2">Добавьте свой первый продукт</a>
            {% endif %}
          </section>
        {% endif %}
      </div>
    </div>
  </main>
{% endblock content %}

digital_store/templates/shop/shop_list.html
{% extends 'base.html' %}
{% block title %} Страница магазинов {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Digital Marketplace</h1>
          <p class="lead text-muted">Еще нет магазина? Можешь открыть прямо сейчас и оказаться в этом списке!</p>
          <p>
            <a href="{% url 'shop:create_shop' %}" class="btn btn-secondary my-2">Открыть магазин</a>
          </p>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    <div class="album py-3 bg-white" style="margin:auto;width:60%">
      <section class="py-5 text-center container">
        {% if page_obj %}
          <h2>Магазины</h2>
        {% else %}
          <h2>Магазинов нет, будь первым!</h2>
        {% endif %}
      </section>
      <div class="container" style="width:90%">
        <div class="row">
          {% for shop in page_obj %}
            {% include 'includes/shop_card.html' %}
            {% if forloop.last %}
            {% else %}
              <hr style="margin-top:10px"></hr>
            {% endif %}
          {% endfor %}
        </div>
        <div class="d-flex align-items-center justify-content-center">
          {% include 'includes/paginator.html'%}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

digital_store/templates/shop/user_shops.html
{% extends 'base.html' %}
{% block title %} Страница магазина {% endblock title %}
{% block content %}
  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Здесь находятся ваши магазины</h1>
          <h4 class="text-muted">Отслеживайте статус вашего магазина, редактируйте и добавляйте новые!</h4>
          <div class="container" style="margin-top: 20px">
            {% if shops_exists %}
              <a href="{% url 'shop:create_shop' %}" class="btn btn-outline-primary me-2">Добавить новый магазин</a>
            {% else %}
              <a href="{% url 'shop:create_shop' %}" class="btn btn-outline-primary me-2">Добавьте ваш первый магазин</a>
            {% endif %}
          </div>
        </div>
      </div>
    </section>
    <hr class="hr-dashed-gradient"></hr>
    <div class="album py-3 bg-white" style="margin:auto;width:60%">
      <div class="container" style="width:90%">
        <div class="row">
          {% for shop in page_obj %}
            {% include 'includes/shop_card.html' %}
            {% if forloop.last %}
            {% else %}
              <hr style="margin-top:10px"></hr>
            {% endif %}
          {% endfor %}
        </div>
        <div class="d-flex align-items-center justify-content-center">
          {% include 'includes/paginator.html'%}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}